### ISSUE TITLE
CPU Monitor: all the cores being bunched into one long bar instead of showing each core separately. 

### ISSUE THREAD

**Issue by senappa** [fflewddur/tophat#101]
On the CPU monitor, I have 'show each core' selected, but when first booting up the system, or if the system was locked, coming back from sleep, etc - the bar always initially shows one extremely long bar - it's as if all the cores are all added up.

![Screenshot from 2023-08-05 16-47-29](https://github.com/fflewddur/tophat/assets/57263714/74b2064d-6663-4318-8751-310f69ba1450)

However, once toggle the 'show each core' setting, it seems to revert back to showing each core as it should (until I reboot the system, lock the system, etc. and it will revert back to the one long bar above).

![Screenshot from 2023-08-05 16-49-06](https://github.com/fflewddur/tophat/assets/57263714/2c97cbb9-09c0-46c2-97c8-ad8b9c46ff04)

I think this might be happening if my panel is set to the left, at the default panel thickness of 48px might be too thin - at 59px exactly this behavior is no longer observed, or if I have the dash panel on top position. 

Wondering if this can be adjusted so that it'll still show all core graphs correctly without having to widen the panel from its default width.

**Comment by fflewddur** [comment]
Thanks for the report! This is definitely a bug, and I'll admit I haven't tested TopHat with vertical panels recently. Will look into what's happening here as soon as I get a chance.
