### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by LostinSpacetime** [fflewddur/tophat#108]
Are there any plans to support Gnome 45?
I can help with testing.

**Comment by enecciari** [comment]
Hi, I have a version compatible with Gnome 45 in Branch 45 of https://github.com/enecciari/tophat.git, I don't make the pull request because I think it is necessary to create a branch for this version that is not compatible with the 44 and previous version.

**Comment by LostinSpacetime** [comment]
> Hi, I have a version compatible with Gnome 45 in Branch 45 of https://github.com/enecciari/tophat.git, I don't make the pull request because I think it is necessary to create a branch for this version that is not compatible with the 44 and previous version.

I successfully tested on Fedora 39. Thank you! :)

**Comment by SeokYoung-Ahn** [comment]
Please update gnome 45. Thank you.

**Comment by fflewddur** [comment]
Thanks for looking into this, @enecciari! I wanted to say that yes, I plan to support GNOME 45, but am currently out on baby bonding leave and haven't really found the time to dig into it. I've been proud to keep TopHat compatible with older GNOME releases and really don't want to break that because of this change. In the worst case, I'll try to get a separate version for GNOME 45 onto extensions.gnome.org, but I'm not sure maintaining two code bases will be sustainable going forward.

**Comment by flipphillips** [comment]
the @enecciari branch working fine w/ Ubuntu 23.10, fwiw.

**Comment by 0Raik** [comment]
@enecciari Thanks for the work! Tried with Manjaro latest and could not install. Maybe I'm doing somthing wrong?
Here is my process...

Went to https://github.com/enecciari/tophat
Clicked on CODE, downloaded ZIP
Followed the instructions of OP, the command `unzip ~/Downloads/tophat-main.zip -d ~/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io`
Log out. Nothing. Restarted. Nothing. It doesn't show up in my extensions.

Thank you for the time and effort.

**Comment by mrnugget** [comment]
@0Raik you need to here: https://github.com/enecciari/tophat/tree/45 — Note the `/tree/45` at the end, that specifies the branch to be `45`.

**Comment by bigbear3001** [comment]
Just upgraded to Ubuntu 23.10 now I'm missing this, is there an easy way to install this with the Extension Manager?

**Comment by 0Raik** [comment]
@bigbear3001 No. It only manages extensions which might look like an oversight, not being able to install from there but its pretty simple:

Download https://github.com/enecciari/tophat/archive/refs/heads/main.zip
Open terminal and paste `unzip ~/Downloads/tophat-main.zip -d ~/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io`
Restart or log out. 

Alternatively open file manager, extract zip contents in ~/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io and restart/log out.

The ~ means home. Your home folder. If you can't see /.local folder its hidden. CTRL + H to show them.

**Comment by ap-wtioit** [comment]
Thanks, had to take the new gnome45 file from https://github.com/fflewddur/tophat/releases:

https://github.com/fflewddur/tophat/releases/download/v11/tophat@fflewddur.github.io.v11.gnome45.shell-extension.zip

And use `unzip ~/Downloads/tophat\@fflewddur.github.io.v11.gnome45.shell-extension.zip -d ~/.local/share/gnome-shell/extensions/tophat@fflewddur.github.io` now it works again.
