### ISSUE TITLE
[BUG] System lag every 5 seconds

### ISSUE THREAD

**Issue by clsty** [fflewddur/tophat#112]
After a reboot, the system began repeating a 5-seconds period: 2 seconds as normal, then 3 seconds as "paused"(can't move mouse, can't use keyboard, screen frozen).

This phenomenon disappeared when I disabled TopHat.

Also, I tried disable all switches on TopHat's configuration panel. Not worky.

Refresh speed: medium
(And when I set it to "Slow", the length of period becomes about 8 seconds, in which 2 seconds are laggy. I didn't try "Fast" to prevent a complete system freeze.)

System: Arch Linux, Gnome.

**Comment by theCalcaholic** [comment]
Same symptoms here.

Fedora 39, Gnome 45 (has been the same on earlier versions)

**Comment by nickuc** [comment]
I have the same problem, it happens every time I try to copy a large file. Disabling the extension solves the problem.

Arch Linux, Linux 6.7.6-arch1-2, gnome-shell 45.4-1, wayland 1.22.0-1

**Comment by fflewddur** [comment]
I believe I tracked down the culprit for this and resolved it. The fix will be included in v16 later this year.

**Comment by fflewddur** [comment]
This has been resolved in TopHat v16.
