### ISSUE TITLE
Use system accent color for charts

### ISSUE THREAD

**Issue by fflewddur** [fflewddur/tophat#12]
Once libadwaita makes this possible, default to using the user's preferred accent color for charts.

**Comment by lkraav** [comment]
> Once libadwaita makes this possible, default to using the user's preferred accent color for charts.

Which libadwaita version are we waiting for?

**Comment by fflewddur** [comment]
Unfortunately I've no idea. I just checked again, but still don't see any way to get this value programmatically, and using Adwaita symbols like @accent_color in the extension stylesheet don't work.

**Comment by fflewddur** [comment]
Completed for TopHat v16.
