### ISSUE TITLE
Showing unsupported version in Gnome 46

### ISSUE THREAD

**Issue by deephack1982** [fflewddur/tophat#124]
On upgrading to Gnome 46 I'm unable to start the extension anymore and it displays unsupported version.

**Comment by deephack1982** [comment]
Just noticed however that the current version of shell-version in metadata.json does list version 46 so I guess we just need a new release.

**Comment by mattia-b89** [comment]
I guess we can easily close this issue since GNOME 46 is currently supported  
(while the latest, 47 isn't yet...)

Arch Linux w/ GNOME 46.5
