### ISSUE TITLE
Error loading tophat extension: Clutter typelib file not found

### ISSUE THREAD

**Issue by Spockologist** [fflewddur/tophat#125]
### Description
When attempting to access the settings of the `tophat` extension, an error is thrown related to the Gnome Shell's Clutter library. It seems that the typelib file for Clutter is not found, which is required for the extension to function properly.

### Error Message
The following error message is displayed:
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

### Stack Trace
The issue can be traced back to the following stack trace:
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://Clutter:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

### Steps to Reproduce
1. Install the `tophat` extension from the Gnome Extensions website or via the Gnome Tweak Tool.
2. Attempt to open the settings for the `tophat` extension.
3. The error message appears and settings cannot be accessed.

### Expected Behavior
The settings dialog for the `tophat` extension should open without any errors.

### Actual Behavior
An error message is displayed and the settings cannot be accessed due to a missing Clutter typelib file.

### System Information
- Gnome Shell Version: 45.2
- `tophat` Extension Version: Current
- Distribution: Ubuntu 23.10
- Installation method of extension: Gnome Extensions website

---

Please let me know if you need any further information or if there are any known workarounds for this issue.

Thank you for your assistance!

**Comment by nongthaihoang** [comment]
`sudo apt install gir1.2-gtkclutter-1.0`

**Comment by UniqueTokens** [comment]
On Fedora 40:

`sudo dnf install clutter-gtk`

**Comment by xChAmeLIoNz** [comment]
> On Fedora 40:
> 
> `sudo dnf install clutter-gtk`

I'm still getting the error after installing this package

@UniqueTokens

**Comment by xChAmeLIoNz** [comment]
After installing, it needs a restart in order to work.

**Comment by kangalio** [comment]
Can a GNOME extension declare external dependencies like this? If so, it would be very neat to have that.

If not, maybe tophat could somehow catch this error and add its own message that either links to this issue or suggests the clutter installation command-lines for a few common distros

**Comment by fflewddur** [comment]
I've removed the clutter dependency, so this shouldn't be a problem for future releases of TopHat. Thanks for reporting it!
