### ISSUE TITLE
its not working in Ubuntu 23.10

### ISSUE THREAD

**Issue by mtariqsajid** [fflewddur/tophat#131]
I am not able to install in ubuntu 23.10 and i don't know how to to read the error logs of the extension

**Comment by mtariqsajid** [comment]
please check it

@fflewddur @noirbizarre @flozz @mrnugget @Vistaus

**Comment by Vistaus** [comment]
I don't know why you tagged me. I'm just a translator and I don't use 23.10 (and I advise you the same, as 23.10 will be obsolete soon).

**Comment by mtariqsajid** [comment]
@fflewddur please update it for ubuntu 24

**Comment by fflewddur** [comment]
TopHat does support Ubuntu 24.04 and the forthcoming 24.10. Are you still having issues with either of these releases?
