### ISSUE TITLE
gnome-system-monitor button disappeared

### ISSUE THREAD

**Issue by pszemus** [fflewddur/tophat#139]
None of TopHat windows (Processor, Memory, Network) does have a gnome-system-monitor button any more:

![image](https://github.com/user-attachments/assets/1a064095-f9b7-4496-87dd-89e74a379e71)

Fedora 40
Wayland @ Gnome 46

**Comment by fflewddur** [comment]
This should be fixed in v15, let me know if it's still an issue.
