### ISSUE TITLE
Ubuntu 24.04 freezes after connecting to VPN

### ISSUE THREAD

**Issue by goldmont** [fflewddur/tophat#140]
OS: Ubuntu 24.04.1 LTS
Kernel: 6.8.0-44-generic
Gnome: 46
Windowing system: X11

---

Hi,

after connecting to a VPN via Network Manager, TopHat makes the whole system freeze and there's no way but pressing the reset button of my PC.

I only have a few extensions installed:
![image](https://github.com/user-attachments/assets/e028618e-43a5-4652-8d70-db5c43481efe)

By disabling TopHat extension, the problem disappear.

**Comment by fflewddur** [comment]
Thanks @goldmont! I think this has already been resolved in the development branch of TopHat, but will be sure to test it before releasing v16.

**Comment by fflewddur** [comment]
Confirmed that connecting and disconnecting Mozilla VPN in Ubuntu 24.04 no longer results in desktop freezes.
