### ISSUE TITLE
Showing unsupported version in Gnome 47

### ISSUE THREAD

**Issue by tachtler** [fflewddur/tophat#142]
Hi,

first of all, thank you for sharing TopHat! 

Could you please update to GNOME version 47?

Thank you in advance.
Klaus.

**Comment by mrbubzie** [comment]
highly double this is going to get updated yout better off looking at forks and building from source.  original dev ha
snt touched in 6 months

**Comment by TarsiSurdi** [comment]
That's sad :( I really like this extension and came to this repo in order to see if anyone had reported an issue on GNOME 47 - the graphs aren't being drawn. It seems pointless to even open the issue now...

**Comment by tachtler** [comment]
Hi,

I switch to https://extensions.gnome.org/extension/6682/astra-monitor/

Greetings
Klaus.

**Comment by tachtler** [comment]
Done for me.
