### ISSUE TITLE
Something gone wrong when tried to configure TopHat

### ISSUE THREAD

**Issue by iRomanyshyn** [fflewddur/tophat#149]
The settings of extension tophat@fflewddur.github.io had an error:
```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
  @gi://Clutter:3:25
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
```

**Comment by iRomanyshyn** [comment]
Of course, resolved by installing a `clutter.x86_64` package on Fedora, but it is not mentioned anywhere. It is better to include this in the description of the extension on extensions.gnome.org as well as here.

**Comment by fflewddur** [comment]
Thanks for reporting this, @iRomanyshyn. Clutter was never intended to be a required dependency for TopHat, and this has been fixed in the development version. I'm going to leave this issue open until TopHat 16 is released, in case anyone else runs into the same problem.

**Comment by fflewddur** [comment]
Closing because Clutter is no longer a dependency of TopHat, as of the v16 release.
