### ISSUE TITLE
Add ability to change meter/chart color

### ISSUE THREAD

**Issue by fflewddur** [fflewddur/tophat#15]
Create a user preferences pane and add a control for the user to select a different color for meters/charts.

Should also support a different secondary color (currently needed for the network upload chart).

**Comment by lkraav** [comment]
> Should also support a different secondary color (currently needed for the network upload chart).

Did this idea not make it?

43: I'm looking to indicate when CPU and memory get into "red hot" levels.

**Comment by fflewddur** [comment]
Yes, this shipped with TopHat v5, but doesn't sound like what you're looking for--this allows you to set the meters to your preferred color instead of the default teal. I'll open a separate issue to track this idea.
