### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by jawwad9226** [fflewddur/tophat#151]
Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
 and when i tried to to install that
jawwad-linux@jawwad-linux:~$ sudo apt install libglib2.0-0 libgtop2.0-0

[sudo] password for jawwad-linux: 

Note, selecting 'libglib2.0-0t64' instead of 'libglib2.0-0'

Error: Unable to locate package libgtop2.0-0

Error: Couldn't find any package by glob 'libgtop2.0-0'

**Comment by fflewddur** [comment]
If you're running Ubuntu or Debian, the command you probably want is `sudo apt install gir1.2-gtop-2.0`.

**Comment by fflewddur** [comment]
Closing since these dependencies are no longer required as of TopHat v16.
