### ISSUE TITLE
Disk space available space disappeared

### ISSUE THREAD

**Issue by metal3d** [fflewddur/tophat#155]
Hi,

For a while, I had got the disk available space that was very useful. It disappeared for days.

Is there any chance to make it displayed again ?

![image](https://github.com/user-attachments/assets/5de558af-7f5c-4d10-af94-bc7d290b29d0)

![image](https://github.com/user-attachments/assets/16c0f6bd-415d-4439-a628-5414562df693)

**Comment by mattia-b89** [comment]
check version 16 release note: https://github.com/fflewddur/tophat/releases/tag/v16

**Comment by SelfRef** [comment]
I really hope it'll be reintroduced sooner than later. I regularly run out of space, so I look at that meter very often.

**Comment by fflewddur** [comment]
Yeah, I missed this monitor, too. It's back in v18, with far fewer bugs.
