### ISSUE TITLE
Add option to hide icons

### ISSUE THREAD

**Issue by mjnaderi** [fflewddur/tophat#20]
Thanks for this great extension.

It would be very nice if there was an option to hide icons, for those who prefer a more simple and minimal look.

![image](https://user-images.githubusercontent.com/2115303/180953975-e913d5a1-2a8d-48a7-ab87-d0e0442a3cd9.png)

**Comment by fflewddur** [comment]
Thanks for the idea! This makes a lot of sense, I'll try to get to it soon; if someone else wants to implement this, I'm open to a patch.
