### ISSUE TITLE
Support transparent theme

### ISSUE THREAD

**Issue by RasheedAZ** [fflewddur/tophat#21]
Hi. Is it possible to make it work with transparent shell theme. My top bar and dock are transparent and it looks like this: 

![image](https://user-images.githubusercontent.com/16827461/181495602-807de07c-bdc2-4bfc-ae6e-f21073178aa3.png)

Thanks.

**Comment by fflewddur** [comment]
Just to clarify, are you asking if the background of the CPU and memory charts can be transparent?

**Comment by RasheedAZ** [comment]
Thanks for replying Todd. Yes, maybe if the background is not a solid colour, it will look less out of place...

**Comment by fflewddur** [comment]
I added some translucency to the chart backgrounds in the latest release. Is this what you were looking for?

![image](https://user-images.githubusercontent.com/5544445/187053308-7edd31d0-e717-4af2-8489-3b1117ca3b40.png)
![image](https://user-images.githubusercontent.com/5544445/187053345-7ebcf23e-bf8f-4ec6-8f1b-fe73b9cd9bde.png)

**Comment by RasheedAZ** [comment]
Looks really great now way better than before on transparent taskbar. Thanks so much.
