### ISSUE TITLE
App icons (VLC, Remmina etc) in top panel split CPU and Memory display

### ISSUE THREAD

**Issue by ijefferies** [fflewddur/tophat#25]
Everything looks fine after startup (see below).
![image](https://user-images.githubusercontent.com/75900977/185676284-2519b2e4-0bfc-465b-8796-4fa182b992ab.png)

If you now run an app that uses the Gnome top panel, the app icon splits the Tophat CPU and Memory display (see below). At least VLC and Remmina have this effect on the display.
![image](https://user-images.githubusercontent.com/75900977/185675361-0dc3049e-e123-421e-a364-640640dfe6c0.png)

Expected behaviour is that the Tophat usage displays remaining together. If you subsequently disable/enable a Gnome extension (seems like doesn't matter which one), the icon and display order is corrected (see below).
![image](https://user-images.githubusercontent.com/75900977/185675695-66f57b56-5c9f-496a-818e-debb1b1220d3.png)

This bug can be reproduced every time on this system.
![image](https://user-images.githubusercontent.com/75900977/185676106-187bd0dc-dec5-4a61-b56f-4ab7e358d5c3.png)

**Comment by fflewddur** [comment]
Thanks for the report! I'd love to use a single widget for all of the indicators, which would prevent this problem, but I haven't figured out how to do that while also having separate drop-downs with process/memory/network details for each indicator. Once I or another contributor can get that working, I think it will resolve this issue.

**Comment by ijefferies** [comment]
That's a shame, hopefully you (or someone) can come up with a solution in the near future. Aside from this bug, it's a great extension (and looks a lot more modern than System-Monitor_next).

**Comment by ijefferies** [comment]
OK, how about this. Include an option to place all app widgets to the right of the centre date/time widget (rather than right side). 

Although this won't fix the problem of widgets splitting, the chance of additional widgets being  added to the centre panel mid session is highly unlikely so it would have the effect of keeping all widgets together. What do you think, is this an easy addition to the code?

**Comment by fflewddur** [comment]
I'm not sure if this would be easy (or even possible--I'm learning a lot about the modern GNOME shell by building this extension, I haven't done much with GNOME since the 2.x days), but I'm open to a PR adding this option. Long term, I'd still like to get all of the indicators into a single top bar container.

**Comment by fflewddur** [comment]
I tracked this down to the appindicator shell extension: it inserts itself after the first item in the panel, instead of the the start of panel box. The above PR should fix this behavior if it gets merged.

**Comment by jvalrog** [comment]
> Thanks for the report! I'd love to use a single widget for all of the indicators, which would prevent this problem, but I haven't figured out how to do that while also having separate drop-downs with process/memory/network details for each indicator. Once I or another contributor can get that working, I think it will resolve this issue.

My 2 cents. You could use a single drop-down where you display what the user has enabled, separated by a line, like this mockup:

![image](https://user-images.githubusercontent.com/456311/187632587-2a536108-328e-4c4d-945e-c5dba81f7da7.png)


That way you can have a single widget instead of 3. They should share the same arrangement though so all graphics are lined up.

**Comment by ijefferies** [comment]
Just tried again, works a treat. Thanks for fixing.
