### ISSUE TITLE
Add a setting to change the position in the panel

### ISSUE THREAD

**Issue by mathias-linkx** [fflewddur/tophat#26]
Thanks for the great extension.

It is common for extensions to allow users to decide where to display the widget in the panel.
Adding a setting to choose to display "far left", "left", "center", "right", "far right" would allow user to better use the screen space.

For instance I would like to put the monitors on the left, as right contains status icons and that area gets visually cluttered like this.

**Comment by fflewddur** [comment]
Great idea, thanks for the suggestion! I'm working on including this with the next release.

**Comment by mathias-linkx** [comment]
Awesome, can't wait for the next version. Cheers !
