### ISSUE TITLE
System log is spammed by non-existant interfaces

### ISSUE THREAD

**Issue by jvalrog** [fflewddur/tophat#30]
I don't exactly know if this is because the extension, but after my VPN is shut down, the logs show gnome-shell trying to access that device constantly.

Example:

```
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/tx_packets": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/rx_bytes": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/tx_bytes": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/rx_errors": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/tx_errors": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/vpn/statistics/collisions": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/virtual0/statistics/rx_packets": No such file or directory
sep 06 14:14:25 ubuntu gnome-shell[4160]: glibtop(c=4160): [WARNING] Failed to open "/sys/class/net/virtual0/statistics/tx_packets": No such file or directory
```

Both **vpn** and **virtual0** are temporary devices and it looks like they are not removed from the watch list of the extension once they are deleted??

[update] Can confirm it's the extension, once I disable it, the spam ends.

**Comment by fflewddur** [comment]
Thanks for reporting this! I think you're right, this seems like it's related to how TopHat is using libgtop, though I haven't been able to replicate it myself yet. Does the log spam occur roughly every two seconds?

**Comment by fflewddur** [comment]
I might have tracked this down, though I wasn't able to replicate it; can you let me know if this change resolves the issue for you?

**Comment by jvalrog** [comment]
> I might have tracked this down, though I wasn't able to replicate it; can you let me know if this change resolves the issue for you?

I'll try later today, thanks

**Comment by nekohayo** [comment]
I've also experienced this, in my case on my desktop computer it's spamming this every few seconds, as can be seen with `journalctl -f`:

`gnome-shell[832185]: [TopHat] Error reading /sys/class/hwmon/hwmon2/temp1_input: Error opening file /sys/class/hwmon/hwmon2/temp1_input: No such file or directory`

It should probe for the existence of such files before trying to access them, and fail gracefully and silently.

**Comment by fflewddur** [comment]
Thanks for reporting this @nekohayo! You're right, I'll look at fixing this for the next release.
