### ISSUE TITLE
icon and font sizes appear too small

### ISSUE THREAD

**Issue by mattia-b89** [fflewddur/tophat#40]
![Screenshot from 2022-11-08 17-49-06](https://user-images.githubusercontent.com/545463/200637437-cd16730d-b6a2-4de4-b15b-c1b692eb5926.png)

starting from the screenshot above, I'd like to share with you three enhancements:

1. shrink unused space at right
2. avoid trimming data at right e.g. (unit of measurement, here MB)
3. increase font size for network speeds in the top bar

**Comment by fflewddur** [comment]
Which distribution are you using? That looks like a rendering bug; for comparison, this is what the menu should look like (on Ubuntu 22.04.1):
<img src="https://user-images.githubusercontent.com/5544445/201490273-2e6d6fb2-df27-4ae7-a2e6-d23a74ed5a15.png" width="50%" height="50%">

**Comment by mattia-b89** [comment]
I am on Arch Linux, extension installed via `extension-manager`

PS: bottom buttons are different, too

**Comment by fflewddur** [comment]
I released TopHat v5 last night, which includes the newer interface from my screenshot. I tested this on an up-to-date Arch install with the default GNOME theme and it rendered as expected. Let me know if you're still having this problem with the latest release!

**Comment by mattia-b89** [comment]
thanks! I updated and issues 1. & 2. are fixed, but 3. got worse
here is a screenshot:
![Screenshot from 2022-11-30 08-32-51](https://user-images.githubusercontent.com/545463/204734799-f30a31eb-e080-458e-a798-bf9f921f5c20.png)

compared to your screenshots, the icons of mine (as well as text and graphs) are way smaller than yours:
- yours almost fit the height of the bar
- mine are the half of the height of it

do you agree?

**Comment by fflewddur** [comment]
Yeah, I see what you mean. Are you using a custom theme, the 'large text' accessibility setting, or any other GNOME extensions to adjust the text and icon size in the top bar? I'd like to replicate this myself to understand what's going on.

**Comment by mattia-b89** [comment]
No custom theme neither extensions which alter topbar;  
I've just set up Scaling Factor to 1.5 (Accessibility > Large Text set it to 1.25 but with Tweaks you can set it to any value...)

**Comment by fflewddur** [comment]
Great, thanks for the details! I'll take a look at replicating this as soon as I can.

**Comment by mattia-b89** [comment]
Thanks for the work!  
As soon as a new version goes out, I will give you a feedback!

**Comment by mattia-b89** [comment]
Now, it's far better

![Screenshot from 2022-12-28 08-34-35](https://user-images.githubusercontent.com/545463/209776007-9dc38617-3f58-4b7f-9dc5-263226c7b783.png)
