### ISSUE TITLE
Cpu graph shows 13 bars with a 12 core cpu

### ISSUE THREAD

**Issue by WiseroOrb** [fflewddur/tophat#41]
![immagine](https://user-images.githubusercontent.com/50355292/200820828-c53c8bc1-693c-4b80-afc0-68ac8e627d49.png)
As you can see, the cpu graph shows 13 bars, but I have only 12 logical cores. The last one never goes above 0.

Using on a openSuse tumbleweed distro.

**Comment by fflewddur** [comment]
Huh. That's an interesting one. I'm not sure what might be going wrong; out of curiosity, what type of CPU do you see this on?

**Comment by WiseroOrb** [comment]
i7-8750H, mobile.

**Comment by WiseroOrb** [comment]
Hi tried to skim through the code, but I couldn't find any cause

**Comment by WiseroOrb** [comment]
Somehow it's fixed now. Maybe some library got fixed. That's the life on a rolling release
