### ISSUE TITLE
Feature request: option to adjust font size for network speed

### ISSUE THREAD

**Issue by minico** [fflewddur/tophat#46]
could you please add an option to ajdust the font of network speed,
I'd like to set it larger.

**Comment by fflewddur** [comment]
I'm looking into why the font appears so small under certain conditions for #40. Are you seeing something similar? I'd like to avoid adding a setting if possible and instead follow the system theme or accessibility setting.

**Comment by minico** [comment]
I use a monitor of 4K resolution and scaled the font to 200%;
here is my status bar:
https://i.postimg.cc/sf0MkR08/Screenshot-20221204174041-746x94.png

**Comment by mattia-b89** [comment]
check out new release!

**Comment by fflewddur** [comment]
Hi @minico , the latest release of TopHat should make the text much more legible. Does this resolve your issue?

**Comment by minico** [comment]
greate, the new version works perfect, thx a lot.

**Comment by fflewddur** [comment]
Awesome, glad to hear it!
