### ISSUE TITLE
CPU temperature shown as n/a

### ISSUE THREAD

**Issue by olfuerniss** [fflewddur/tophat#69]
Just switched to a Mini PC (Minis Forum UM690) with an AMD Ryzen 6900hx mobile processor. Just wondering why the CPU temperature is shown as `n/a`. 

![image](https://user-images.githubusercontent.com/30932609/213845582-21d0a879-42f0-4982-bb1f-39a79138c69a.png)

As far I was able to read the code, it should find the temperature from `/sys/class/hwmon/hwmon3/temp1_input`

![image](https://user-images.githubusercontent.com/30932609/213845675-7e3e0606-e3d9-4d4c-b0c1-d52f2f333767.png)

**Comment by olfuerniss** [comment]
P.S. Using Tophat 6 on Fedora 37

**Comment by fflewddur** [comment]
Thanks for reporting this! It should already be fixed as part of https://github.com/fflewddur/tophat/pull/58, so the next release will hopefully resolve your issue. I'll leave this open until then to confirm.

**Comment by olfuerniss** [comment]
Thanks Todd, version 7 fixed it. :-)

![Bildschirmfoto vom 2023-01-28 06-08-31](https://user-images.githubusercontent.com/30932609/215243370-6e8a59b8-341d-4f28-8e82-f85717c403a6.png)

**Comment by fflewddur** [comment]
Great, thanks for confirming!
