### ISSUE TITLE
[enhancement] disk activity

### ISSUE THREAD

**Issue by mattia-b89** [fflewddur/tophat#74]
New **disk activity** is great;  
anyway, the indicator, is always green (maybe it points to disk usage rather than disk activity?!)  
making it not useful, as it should be:  
- disk activity changes rapidly over time
- disk usage does not change rapidly over time

I share a screenshot showing that upper indicator is fully green while chart is almost _empty_:
![Screenshot from 2023-02-11 09-12-15](https://user-images.githubusercontent.com/545463/218247880-9edf8ce9-03f0-494e-96fb-a1f9c2240bb5.png)

**Comment by fflewddur** [comment]
Yes, it shows filesystem usage, and this is by design. In the future I'd like to also support disk activity, similar to the network monitor.
