### ISSUE TITLE
Is is possible for the svg icons to follow the panel text and icon colors?

### ISSUE THREAD

**Issue by hrqmonteiro** [fflewddur/tophat#82]
I have a light theme set that makes all of my panel text and icons dark, but TopHat icons doesn't follow it:

![Screenshot from 2023-04-14 13-16-39](https://user-images.githubusercontent.com/17055027/232099755-d8497baa-1e47-4804-8dbb-6984805386e7.png)

Is it possible to change it so it matches it? I tried messing around with the classes in the files from the extension but only wasn't able to make the background-color properly changes, like so:

```
.tophat-panel-icon {
  background-color: red;
  color: black;
}
```

![Screenshot from 2023-04-14 13-17-40](https://user-images.githubusercontent.com/17055027/232099963-7c3bef0e-5fbe-4326-b524-5c4ac2adbcc4.png)

Any help on it? It would be very nice if the icons matched!

**Comment by hrqmonteiro** [comment]
Update:

I added this functionality and opened a PR [here](https://github.com/fflewddur/tophat/pull/84)

**Comment by fflewddur** [comment]
This is awesome, thanks for working out how to fix this!
