### ISSUE TITLE
Error during update 

### ISSUE THREAD

**Issue by MZHI** [fflewddur/tophat#96]
Hi! I just try to update tophat using gnome extenstion page and got error, and after that my resource monitor stop working and now I can't install it again. Ubuntu 22.04. Have any ideas? I can provide additional info, just tell me what

**Comment by weatheredwatcher** [comment]
Hey!  Not involved, just a happy user such as your self!  What you need to do is go to the Releases page and download version 10 of the extension and follow the instructions for installing the extension manually.  Then, you need to hit <alt>-<f2> to bring up the shell run dialog and run the command 'r' to restart the shell....then tophat will run again!  Then you can just wait for an update that fixes the error!!

**Comment by MZHI** [comment]
> Hey! Not involved, just a happy user such as your self! What you need to do is go to the Releases page and download version 10 of the extension and follow the instructions for installing the extension manually. Then, you need to hit alt-f2 to bring up the shell run dialog and run the command 'r' to restart the shell....then tophat will run again! Then you can just wait for an update that fixes the error!!

This helped me. I select version of shell == 42 and version of extension == 10, and now it works again! Thank you a lot! I can't imagine my desktop without this application now)
